baseURL = "https://hollis.computer/"
languageCode = "en-us"
title = "hollis.computer"
theme = "terminal"

[params]
  contentTypeName = "posts"
  themeColor = "purple"
  showMenuItems = 2
  showLanguageSelector = false
  fullWidthTheme = false
  centerTheme = true
  showLastUpdated = false

[params.twitter]
  creator = "david_hollis"
  site = "https://hollis.computer/"

[languages]
  [languages.en]
    languageName = "English"
    title = "hollis.computer"
    subtitle = "hollis's computer stuff"
    owner = ""
    keywords = ""
    copyright = "2021 David Hollis"
    menuMore = "Show more"
    readMore = "Read more"
    readOtherPosts = "Read other posts"
    newerPosts = "Newer posts"
    olderPosts = "Older posts"
    missingContentMessage = "Page not found..."
    missingBackButtonLabel = "Back to home page"

    [languages.en.params.logo]
      logoText = "hollis.computer"
      logoHomeLink = "/"

    [languages.en.menu]
      [[languages.en.menu.main]]
        identifier = "home"
        name = "home"
        url = "/"
